"""add_google_review_url_funnel_slug_to_locations

Revision ID: 1568af9093c6
Revises: e0721cb02635
Create Date: 2026-06-29 23:57:11.235787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1568af9093c6'
down_revision: Union[str, None] = 'e0721cb02635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('google_review_url', sa.String(length=500), nullable=True))
    op.add_column('locations', sa.Column('funnel_slug', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'locations', ['funnel_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_column('locations', 'funnel_slug')
    op.drop_column('locations', 'google_review_url')
    # ### end Alembic commands ###
