"""initial_schema

Revision ID: e0721cb02635
Revises: 
Create Date: 2026-06-29 23:48:56.903557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0721cb02635'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'is_synced',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'is_synced',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1),
               existing_nullable=False)
    # ### end Alembic commands ###
